version: '3.1'

services:
  local-postgres-compose:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bluecoding_database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge